site_name: Open Data Manager Documentation
site_url: https://mctep.github.io/mkdocs-example/

nav:
  - Packages to install:
      - 00. Packages to install/1. Genestack python client/README.md
      - Genestack python client: 00. Packages to install/1. Genestack python client/README.md
      - Genestack auxiliary scripts: 00. Packages to install/2. Genestack auxiliary scripts/README.md
  - Users:
      - 01. Users/User creation/README.md
      - Users creation: 01. Users/User creation/README.md

theme:
  name: material
  palette:
    primary: custom
    accent: custom
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
extra:
  version:
    provider: mike
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - tables
  - md_in_html
  - toc:
      permalink: true
